### ISSUE TITLE
Nest can't resolve dependencies of the SchedulerMetadataAccessor

### ISSUE THREAD

**Issue by catherine-rmdy** [nestjs/schedule#1019]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

N/A

### Versions

1.0.2 -> 2.1.0

### Describe the regression

@nestjs/schedule module is no longer working after upgrading all nestjs packages to the latest versions and node v18.7.0:

Nest can't resolve dependencies of the SchedulerMetadataAccessor (?). Please make sure that the argument Reflector at index [0] is available in the ScheduleModule context.

### Minimum reproduction code

1. package.json
...
    "@nestjs/apollo": "^10.0.22",
    "@nestjs/common": "^9.0.11",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.11",
    "@nestjs/graphql": "^10.0.22",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/platform-express": "^9.0.11",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/typeorm": "^9.0.1",
    "@types/cron": "^2.0.0",
    "apollo-server-core": "^3.10.1",
    "apollo-server-express": "^3.10.1",
...

2. app.module.ts
@Module({
  imports: [ScheduleModule.forRoot(), ...],
})

### Expected behavior

Expected Nest to build when using @nestjs/schedule .

**Comment by micalevisk** [comment]
you problably got two versions of `@nestjs/common` in your project. Share a minimum repro.

# [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by catherine-rmdy** [comment]
Thank you for the quick reply.
1. Ran `yarn why @nestjs/common` , which gave me only one version > 9.0.11
2. Deleted my dist-folder,  threw away all my node-modules, reinstalled and rebuild the application (as suggested in a closed bug-ticket that related to this problem), but still no luck.
3. I will try to come back with a minimum repo as soon as I was able to extract it out of my monorepo.

**Comment by catherine-rmdy** [comment]
When trying to extract the code out, I noticed that the error came from the monorepo.workspaces. 
Adding "@nestjs/common" to the "nohoist" option in package.json, solved it for me. 
Thank you anyway for pointing me in the right direction.
