### ISSUE TITLE
Add a CronExpression.NEVER expression

### ISSUE THREAD

**Issue by xegulon** [nestjs/schedule#1053]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to programmatically choose the expression that I'll put in a `@Cron()` and sometimes (in some environments) I don't want the Cron job to execute. 

### Describe the solution you'd like

I'd like to have a new enum, name `CronExpression.NEVER`, that I can put into the `@Cron`

### What is the motivation / use case for changing the behavior?

The motivation is that it is a clean solution. An alernative would be to use the scheduler registry in main.ts to stop the cron job, but it is less flexible.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by xegulon** [comment]
> Would you like to create a PR for this issue?

Yeah I'll try! Alternatively, what about a `disabled` field in `CronOptions`?

**Comment by kamilmysliwiec** [comment]
Sounds good

**Comment by origranot** [comment]
@xegulon Are you still working on this issue?

**Comment by xegulon** [comment]
@origranot no sorry, would you like to do the PR?
