### ISSUE TITLE
Exceptions not handled in cronjob functions added via SchedulerRegistry

### ISSUE THREAD

**Issue by simon1389** [nestjs/schedule#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When adding a cronjob by using the SchedulerRegistry, exceptions occuring inside the cron-function are not handled and cause the app to exit.
In a previous commit this behavior was fixed when using the `@Cron` annotation (https://github.com/nestjs/schedule/commit/0cdfe8fa0a8b9b5132ecf32692ffe58fa7f229b6)

### Minimum reproduction code

https://github.com/simon1389/nestjs-schedule-bug

### Steps to reproduce

1. npm start
2. See the error on console and the application shutdown

### Expected behavior

I expect the same behavior as when using the `@Cron` syntax.
So the error should be catched.

### Package version

2.1.0

### NestJS version

9.0.0

### Node.js version

16.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by simon1389** [comment]
> 

PR opened

**Comment by simon1389** [comment]
PR opened 😃

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schedule/pull/1084
