### ISSUE TITLE
Vulnerability found in the dependency

### ISSUE THREAD

**Issue by jamesweb1** [nestjs/schedule#1147]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### **Description**

luxon 1.0.0 - 1.28.1
Severity: high
Luxon Inefficient Regular Expression Complexity vulnerability - [GHSA-3xq5-wjfh-ppjc](https://github.com/advisories/GHSA-3xq5-wjfh-ppjc)

### **Screenshots**

No response

### **Additional information**

No response

### Describe the solution you'd like

Upgrade the package cron to v2.2.0 to solve this security issue.

### What is the motivation / use case for changing the behavior?

None

**Comment by micalevisk** [comment]
Should be fixed by #1125
