### ISSUE TITLE
Switch scheduling backend to Croner

### ISSUE THREAD

**Issue by Hexagon** [nestjs/schedule#1164]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

NPM package `cron` is broken in many ways, which you can read about [here](https://github.com/Hexagon/croner#why-another-javascript-cron-implementation). It doesn't receive much (if any) attention. Have a look at their [list of issues](https://github.com/kelektiv/node-cron/issues).

### Describe the solution you'd like

I would recommend you to consider switching from npm package [cron](https://github.com/kelektiv/node-cron) to [croner](https://github.com/Hexagon/croner).

### Teachability, documentation, adoption, migration strategy

I noticed that you have implemented one feature of cron, which isn't supported by croner - the utcOffset. I could implement that if you're interested and think it is a useful feature. So far i've avoided giving that option, as time zones can have different utc offset at different time of year.

### What is the motivation / use case for changing the behavior?

Croner is actively maintained, trusted by pm2, and have 0 active issues.

**Comment by Hexagon** [comment]
"Finished" a draft pull reqest, question about the importance of utcOffset remains.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schedule/pull/1165
