### ISSUE TITLE
Cronjob Management Dashboard

### ISSUE THREAD

**Issue by yasinosman** [nestjs/schedule#1179]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Debugging cronjobs may be tricky sometimes, so it would be really nice if we can see the details of all the active cronjobs

### Describe the solution you'd like

We can have a web UI/cli tool to perform the following activities: 
- List all the cronjobs
- See details of a cronjob (execution date, period etc.)
- (?) Deactivate a cronjob / create new ones

### What is the motivation / use case for changing the behavior?

It would be a great developer experience and a really helpful tool

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
