### ISSUE TITLE
Crons don't start

### ISSUE THREAD

**Issue by mudlee** [nestjs/schedule#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I followed the official [NestJS tutorial](https://docs.nestjs.com/techniques/task-scheduling) to create a cron. Yet it not works. I have no errors at all, but none of my crons run. I'm not a newbie here, I had several NestJS projects, I had no issues till today.
This project however is with the latest nestjs,  with up2date everything.

### Minimum reproduction code

-

### Expected behavior

I would expect crons to be running.

### Package version

3.0.1

### NestJS version

10.0.5

### Node.js version

18.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
