### ISSUE TITLE
Cannot find type definition file for 'cron'

### ISSUE THREAD

**Issue by mjad218** [nestjs/schedule#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When building a Nest js app, the build fails and throws this error: 
```
Step #0 - "Build": > nest build
Step #0 - "Build": 
Step #0 - "Build": �[91m�[91merror�[0m�[90m TS2688: �[0mCannot find type definition file for 'cron'.
Step #0 - "Build":   The file is in the program because:
Step #0 - "Build":     Entry point for implicit type library 'cron'
Step #0 - "Build": 
Step #0 - "Build": �[0mFound 1 error(s).
Step #0 - "Build": 
Step #0 - "Build": The command '/bin/sh -c npm run build' returned a non-zero code: 1
Finished Step #0 - "Build"

```

The bug is actually because `@types/cron` package is deprecated two days ago. 

The `cron` package now ships its own types. 

The simple solution is to update the dependencies. 

- Removing  `@types/cron`, and 
- Updating `cron` to `2.4.0`

### Minimum reproduction code

n/a

### Steps to reproduce

1. nest new
2. npm i @nestjs/schedule
3. npm i 
4. npm run build

### Expected behavior

Build script runs without errors

### Package version

3.0.1

### NestJS version

10.1.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
since `@types/cron` is a dev dependency, you shouldn't have that `@types/cron` installed when installing `@nestjs/schedule`

The steps to reproduce you shared does not reproduces the issue:

Are you sure that `@types/cron` is not on your side? run `npm ls @types/cron`

**Comment by mjad218** [comment]
The bug happens during my CI/CD on GitHub. The weird thing is it does not happen when I build the app locally.

**Comment by mjad218** [comment]
I am using a Dockerfile `node:slim`. 

I am building the Dockerized app locally, will post an update soon

**Comment by micalevisk** [comment]
might be a environment issue then?

anyways. We can drop that dep on `@types/cron` 

![image](https://github.com/nestjs/schedule/assets/13461315/e693d479-56fe-4e88-9a18-0732b6630ae5)

**Comment by mjad218** [comment]
Maybe, I am still checking.

**Comment by belyaev-dev** [comment]
Got the same issue. Deleting `@types/cron` solved the issue for now

**Comment by mjad218** [comment]
Unfortunately, deleting `@types/cron` didn't solve it for me

**Comment by belyaev-dev** [comment]
tried installing `npm install cron` manually?

**Comment by mjad218** [comment]
yes, did that too.

**Comment by mjad218** [comment]
Actually, Installing `cron@2.4.0` solved the issue

**Comment by belyaev-dev** [comment]
Same for me

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schedule/pull/1355
