### ISSUE TITLE
How to stop an actively running cron job?

### ISSUE THREAD

**Issue by CharlesTaylor-Syn** [nestjs/schedule#1412]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am attempting to implement lightweight recurring jobs that be can scheduled dynamically, and also killed dynamically based on timeouts for each job. 

To this end, I looked at the dynamic scheduling API, and saw that jobs can be scheduled or unscheduled at runtime. However, it seemed I would be unable to stop a job that is currently running. 

For example it would be nice to introduce automatic timeouts for a job that has been running for too long.

### Describe the solution you'd like

I'm look for some advice on my situation. 

### What is the motivation / use case for changing the behavior?

See above.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in this repository https://github.com/kelektiv/node-cron
