### ISSUE TITLE
Cron call twice times

### ISSUE THREAD

**Issue by giabao1008** [nestjs/schedule#1417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi. 
I've setup schedule for my application
Here is the codes: 
`@Cron(CronExpression.EVERY_10_SECONDS, {`
`    name: "cron_update_offer_status",`
  `})`
  `async handleUpdateStatusOffer() {`
   ` const currentTimeInUTC = dayjs().utc().format("YYYY-MM-DD HH:mm:ss.SSS");`
   ` this.logger.debug("Cron job executed at " + currentTimeInUTC);`
 ` }`

But seem it call 2 times each run:
<img width="1008" alt="Screenshot 2023-09-14 at 11 13 07" src="https://github.com/nestjs/schedule/assets/30625797/5a815b09-1814-4b95-891f-bfebc019724f">

### Minimum reproduction code

https://github.com

### Expected behavior

sorry is private repo

### Package version

3.0.3

### NestJS version

7.6.1

### Node.js version

v18.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
