### ISSUE TITLE
Using `env` variables in the `@Cron` handle

### ISSUE THREAD

**Issue by Mortefal** [nestjs/schedule#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the @Cron function to create a scheduled job, it fails to read variables from env. I 

### Minimum reproduction code

https://github.com/Mortefal/cron-proof

### Steps to reproduce

1. `npm i`
2. create` .env` file and add `CRON_TEST_STRING `with a valid cron value. eg. `*/10 * * * * *`
3. npm run start
4. expect this error: 

`node_modules\cron\dist\time.js:360
        source = source.toLowerCase();
                        ^
TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

Where i would expect it to register both cron jobs in `app.service.ts`.

### Expected behavior

Where i would expect it to register both cron jobs in `app.service.ts`.

Seems like the @Cron function runs without access to the process.env

### Package version

^4.0.0

### NestJS version

^10.0.0

### Node.js version

v18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> I'll let the Nest maintainers comment on using environment variables in the Cron decorator. However, this may be due to the AppService decorators being loaded before the ConfigModule loads the .env file.

Correct.

For this, you should use the dynamic cron jobs API https://docs.nestjs.com/techniques/task-scheduling#dynamic-cron-jobs
