### ISSUE TITLE
Missing CronJob type generics in SchedulerRegistry.addCronJob

### ISSUE THREAD

**Issue by nerdstep** [nestjs/schedule#1537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `SchedulerRegistry.addCronJob` method should implement the `CronJob` type generics:

```ts
addCronJob<T = null, C = null>(name: string, job: CronJob<T, C>): void;
```

Otherwise a type error occurs when the `onComplete` function is defined.

<img width="681" alt="image" src="https://github.com/nestjs/schedule/assets/535021/d41e30f0-9f1e-4c98-a249-ed8dca5113a1">

### Minimum reproduction code

https://github.com/nestjs/schedule/blob/master/lib/scheduler.registry.ts#L50

### Steps to reproduce

1. Create a new instance of `CronJob` with an `onComplete` callback defined.
2. Call `schedulerRegistry.addCronJob` with the job instance

### Expected behavior

Expected not to receive a type error when `onComplete` callback is defined.

### Package version

4.0.0

### NestJS version

10.3.0

### Node.js version

18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by nerdstep** [comment]
Hey @kamilmysliwiec yeah I can put in a PR for this, no problem.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schedule/pull/1538
