### ISSUE TITLE
Dynamic cron job via `nestjs/schedule` pkg requires `cron` pkg resulting with duplicate `cron` pkgs

### ISSUE THREAD

**Issue by shanike** [nestjs/schedule#1810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

According to [docs](https://docs.nestjs.com/techniques/task-scheduling#dynamic-cron-jobs), a manual cron job is created like so:

```ts
const job = new CronJob(`${seconds} * * * * *`, () => {
  this.logger.warn(`time (${seconds}) for job ${name} to run!`);
});

this.schedulerRegistry.addCronJob(name, job);
job.start();
```

Notice the `CronJob` class is from the `cron` package (and not from the `@nestjs/schedule` package), as mentioned in the [`HINT` in the docs](https://docs.nestjs.com/techniques/task-scheduling#dynamic-cron-jobs:~:text=Import%20CronJob%20from%20the%20cron%20package.).

Because `cron` is a dependency (and NOT a peer-dependency) of `@nestjs/schedule`, if our server also depends on `cron` we end up with 2 `cron` dependencies which is not ideal, and worse: they may be of different versions(!).

This results with the following TypeScript issue:
![image](https://github.com/user-attachments/assets/f6f3e595-4979-4bbf-a82b-b74fff2cfd00)
In text: Argument of type 'import("/home/path/to/project/node_modules/.pnpm/cron@3.1.3/node_modules/cron/dist/job").CronJob<null, null>' is not assignable to parameter of type 'import("/home/path/to/project/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/job").CronJob<null, null>'.
  The types of 'cronTime.source' are incompatible between these types.
    Type 'string | import("/home/path/to/project/node_modules/.pnpm/@types+luxon@3.3.8/node_modules/@types/luxon/src/datetime").DateTime<boolean>' is not assignable to type 'string | luxon.DateTime<boolean>'.
      Type 'DateTime<boolean>' is not assignable to type 'string | DateTime<boolean>'.
        Type 'DateTime<boolean>' is missing the following properties from type 'DateTime<boolean>': getPossibleOffsets, isWeekend, localWeekday, localWeekNumber, and 2 more.ts(2345)

### Minimum reproduction code

https://github.com/shanike/nestjs-schedule-bug-repro

### Steps to reproduce

1. `pnpm start`

### Expected behavior

If `nestjs/schedule` requires me to install the `cron` package -> Then `nestjs/schedule` should have `cron` as a peer-dependency.

Otherwise, `nestjs/schedule` can export any objects/types of the `cron` package once might need when using `nestjs/schedule` and not require us to install the `cron` package ourselves.

### Package version

4.0.0

### NestJS version

10.2.10

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

We use `pnpm` as our package manager.

**Comment by micalevisk** [comment]
as the version of `cron` dependency is pinned, you'll need to exact same version of `cron` in your side as well.

see that version at `npm view @nestjs/schedule dependencies`

**Comment by shanike** [comment]
Thanks for the quick reply.

I understand  using the same version of `cron` will solve the issue, but I still think the better approach is for `nestjs/schedule` to set `cron` as peer-dependency, no? Or to export the `CronJob` class?
