### ISSUE TITLE
Limit only start one task in 2 or more core server.

### ISSUE THREAD

**Issue by toknT** [nestjs/schedule#1840]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In a lot of case , I only need to run one task such as : checking user's subscription, is the discount event is end today ...However if put it on a 2 core cpu server , it start 2 task at same time. 

there is a same issue https://github.com/nestjs/schedule/issues/312 but it's meaning useing cache to schedule task to do that...

### Describe the solution you'd like

Put a task lock in cache (redis)

### What is the motivation / use case for changing the behavior?

No any change just save the resource of server.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/schedule/issues/312#issuecomment-688268349
