### ISSUE TITLE
Scheduled jobs execute multiple times

### ISSUE THREAD

**Issue by HenonoaH** [nestjs/schedule#454]
## I'm submitting
<pre><code>[ ] Bug report</code></pre>

## Current behavior
Every scheduled job runs multiple times.

## Expected behavior
It should be triggered only once for the given cron expression 

## Minimal reproduction of the problem with instructions
<pre><code>
@Cron('* * * * *')
async helloWorld() {
    console.log(new Date());
    console.log('coming');
    console.log(new Date());
}
</code></pre>

This simple hello world scheduled job triggers multiple times every minute.

## Environment

<pre><code>
Nest version: 14.10.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the cron package repository https://github.com/kelektiv/node-cron
