### ISSUE TITLE
feat: use cron name to log error

### ISSUE THREAD

**Issue by ndeitch** [nestjs/schedule#956]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Improve unhandled exceptions inside cron tasks.

### Describe the solution you'd like

Use cron name if provided as context for log.error message.

Update: https://github.com/nestjs/schedule/blob/73f46adcaddf3a413ee1846fc3335718fff1c418/lib/schedule.explorer.ts#L125

from: `this.logger.error(error)`

to: `this.logger.error(error, cronName)`

cronName would be add as param for  `wrapFunctionInTryCatchBlocks` existing method, it can be null if so, use `Scheduler` as default

### Teachability, documentation, adoption, migration strategy

Not sure about add any tip about this in doc.

### What is the motivation / use case for changing the behavior?

Currently when unexpected errors happens only error message is print without much context about where it came from, in big repos with many cron jobs it's hard to find which method thrown the error.

I'm able to implement this PR and understand that it can be considered unnecessary as exceptions should be handled inside each cron.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/10992150/174484664-6255a363-0909-41ac-989e-1a8299e8c39e.png">

**Comment by micalevisk** [comment]
if we implement this, we should change the followin somehow

https://github.com/nestjs/schedule/blob/73f46adcaddf3a413ee1846fc3335718fff1c418/lib/schedule.explorer.ts#L10

so every log will use the cron name instead

**Comment by ndeitch** [comment]
What do you suggest @micalevisk? Should I open a PR and we discuss about the implementation?

**Comment by micalevisk** [comment]
yep, feel free to implement this

**Comment by kamilmysliwiec** [comment]
Feel free to create a PR for this.
