### ISSUE TITLE
Cannot use scheduler with NestJS 9.x

### ISSUE THREAD

**Issue by NoNameProvided** [nestjs/schedule#977]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

2.1.0

### Describe the regression

After upgrading NesJS core and related packages to 9.x the scheduler package doesn't work anymore. On startup the following DI error is raised: 

```
[Nest] 1852  - 07/12/2022, 9:42:10 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the SchedulerMetadataAccessor (?). Please make sure that the argument Reflector at index [0] is available in the ScheduleModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current ScheduleModule?
- If Reflector is exported from a separate @Module, is that module imported within ScheduleModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

Error: Nest can't resolve dependencies of the SchedulerMetadataAccessor (?). Please make sure that the argument Reflector at index [0] is available in the ScheduleModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current ScheduleModule?
- If Reflector is exported from a separate @Module, is that module imported within ScheduleModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })
```

### Minimum reproduction code

- `rm -rf build`
- `rm -rf node_modules`
- `npm ci`
- then start an application with the scheduler included

```ts
import { Module } from '@nestjs/common';
import { APP_GUARD } from '@nestjs/core';
import { ScheduleModule } from '@nestjs/schedule';
import { AuthGuard, ComposeGuard, ResponseValidationCheckGuard } from './guards';

@Module({
  imports: [ScheduleModule.forRoot()],
  providers: [AuthGuard, ResponseValidationCheckGuard, { provide: APP_GUARD, useClass: ComposeGuard }],
})
export class CoreModule {}
```

### Expected behavior

This package works with the latest NestJS version.

**Comment by kamilmysliwiec** [comment]
There were no changes in v9 that could lead to `@nestjs/schedule` not working as expected. 

> If Reflector is a provider, is it part of the current ScheduleModule?

Your dependencies are very likely not "deduped" (https://stackoverflow.com/questions/52781142/what-is-deduped-in-npm-packages-list) + there must be >=2 copies of `@nestjs` packages in your node_modules folder. 

There's a similar issue described & explained in the docs

![image](https://user-images.githubusercontent.com/23244943/178463116-0f7ee1f1-741d-4535-a493-f20cf8ba0812.png)

https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
