### ISSUE TITLE
[feature] Support Schedule Web UI for schedules monitoring 

### ISSUE THREAD

**Issue by YangChoi** [nestjs/schedule#979]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello, Recently I've used @nestjs/schedule in project. 
but I realized there is no web UI for monitoring my cronjob in this library.
I used to use Ruby on Rails, and there is a similar library aka Sidekiq.
It has supported Web UI, so I can check my cronJobs and waiting Queues. 
So I would like to add Web UI for @nestjs/schedule for monitoring.

### Describe the solution you'd like

If I add Web UI for @nestjs/schedule, It would be pretty simple.
There are pages that I want to make,

- page for cronJob List in my server
- page for waiting queues list
- page for checking executed queues

### What is the motivation / use case for changing the behavior?

It was comfortable that I check my cronjob running when I use sidekiq.
so I really hope so, NestJS also can.
And I want to make it.
of course I can check that with AWS CloudWatch but It would be good if it has visibility and Intuition.

I look forward to hearing from you favorable.
Thank you :)

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package :)
